services:
  - type: web
    name: mayan-portfolio-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mayan-portfolio-db
          property: connectionString
      - key: ADMIN_EMAIL
        value: teacher@schoolboard.local
      - key: ADMIN_PASSWORD_HASH
        value: $2b$12$dxbU0strxpxb64MGR6L8buQH/8nfcZfoOxf84g/MUwhKOE7l74jtu
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://temporary-sonic-quasar-zam2ux2.vercel.app
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: mayan-portfolio-db
    databaseName: mayanportfolio
    user: mayanadmin
    plan: free
