services:
  - type: web
    name: mayan-portfolio-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mayan-portfolio-db
          property: connectionString
      - key: ADMIN_EMAIL
        value: mayan9@gmail.com
      - key: ADMIN_PASSWORD_HASH
        value: $2b$12$lkMq2pwFsYY5eyLWbgTN0OG8IwVR7KyHjATkjX5MVMX4INwW0PBOi
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://temporary-sonic-quasar-zam2ux2.vercel.app
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: mayan-portfolio-db
    databaseName: mayanportfolio
    user: mayanadmin
    plan: free
